apiVersion: v1
kind: Service
metadata:
  name: sip-calculator-service
spec:
  selector:
    app: sip-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Use LoadBalancer for cloud K8s or NodePort for local K8s
